=== rpsinghc/maven-projects-springs/java9/conf/resources/designer/Designer.dtd
<!-- DesignerToolbar.xml -->

<!ELEMENT Toolbar (Palettes,Rules?)>

<!ELEMENT Palettes (Palette+)>

<!ELEMENT Palette (Page+)>
<!ATTLIST Palette
    mode CDATA #IMPLIED
>

<!ELEMENT Page (Icon*,Description*,Templates)>
<!ATTLIST Page
    name CDATA #REQUIRED
>

<!ELEMENT Templates (ComponentTemplate)*>

<!ELEMENT ComponentTemplate (NameTemplate+,Icon*,Description+,Properties?,Inputs?,Outputs?)>
<!ATTLIST ComponentTemplate
    name CDATA #REQUIRED
    type (Start|Workstep|Subprocess|External|WebService|Decision|AndJoin|OrJoin|XorJoin|Split|End|StickyNote|Annotation) #IMPLIED
    width CDATA #IMPLIED
    height CDATA #IMPLIED
>

<!ELEMENT Icon EMPTY>
<!ATTLIST Icon
    xml:lang CDATA #IMPLIED
    toolbar CDATA #IMPLIED
    diagram CDATA #IMPLIED
    diagram_bw CDATA #IMPLIED
>

<!-- Backward compatibility: keep both lang and xml:lang. We should remove xml:lang -->
<!ELEMENT Description (#PCDATA)>
<!ATTLIST Description
  lang CDATA #IMPLIED
  xml:lang CDATA #IMPLIED
>

<!ELEMENT Properties (Performer|PerformBy|Precondition|ClosedConnection|Instruction|Milestone|Duration|Priority|PreFunction|PostFunction|AtomicType|PerformingApp|Role|EmailSupport|Subprocess|ManagedAdapter)*>

<!ELEMENT Inputs (Param*)>

<!ELEMENT Outputs (Param*)>

<!ELEMENT Param (Description*, Storage*)>
<!ATTLIST Param
    name CDATA #REQUIRED
    type CDATA "STRING"
    optional (TRUE | FALSE) "FALSE"
>

<!ELEMENT Storage (#PCDATA)>
<!ATTLIST Storage
    type CDATA #REQUIRED
    size CDATA #IMPLIED
    precision CDATA #IMPLIED
    scale CDATA #IMPLIED
>


<!--
Performer
type : user, adapter, subprocess, webservice

AtomicWS     : (name, select, role, count)
ExternalWS   : (class, method)
SubprocessWS : (server, subprocess)
WebServiceWS : (wsdl, service, operation, port/LocalPart/)

Inputs and Outputs defined for ExternalWS
-->

<!ELEMENT Performer (#PCDATA|Inputs|Outputs|Description)*>
<!ATTLIST Performer
  type      CDATA #IMPLIED
  name      CDATA #IMPLIED
  id        CDATA #IMPLIED
  select    CDATA #IMPLIED
  role      CDATA #IMPLIED
  count     CDATA #IMPLIED
  class     CDATA #IMPLIED
  method    CDATA #IMPLIED
  generate  CDATA #IMPLIED
  server    CDATA #IMPLIED
  subprocess CDATA #IMPLIED
  wsdl      CDATA #IMPLIED
  service   CDATA #IMPLIED
  operation CDATA #IMPLIED
  port      CDATA #IMPLIED
  managed   CDATA #IMPLIED
  category  CDATA #IMPLIED
>

<!ELEMENT Performers (Performer*)>


<!ELEMENT PerformBy (#PCDATA)>
<!ELEMENT Precondition (#PCDATA)>
<!ELEMENT ClosedConnection (#PCDATA)>
<!ELEMENT Instruction (#PCDATA)>
<!ELEMENT Milestone (#PCDATA)>
<!ELEMENT Duration (#PCDATA)>
<!ELEMENT Priority (#PCDATA)>
<!ELEMENT PreFunction (#PCDATA)>
<!ELEMENT PostFunction (#PCDATA)>

<!ELEMENT NameTemplate (#PCDATA)>
<!ATTLIST NameTemplate
   xml:lang CDATA #IMPLIED
   count CDATA #IMPLIED
>

<!ELEMENT AtomicType (#PCDATA)>

<!ELEMENT PerformingApp (#PCDATA)>
<!ATTLIST PerformingApp
 type CDATA #IMPLIED
>

<!ELEMENT Role (#PCDATA)>
<!ATTLIST Role
   name CDATA #IMPLIED
>

<!ELEMENT EmailSupport (#PCDATA)>
<!ELEMENT Subprocess (#PCDATA)>

<!-- DesignerRules.xml -->

<!ELEMENT Rules (RuleCategory*)>

<!ELEMENT RuleCategory (Description*,RuleTemplate*)>
<!ATTLIST RuleCategory
   name CDATA #IMPLIED
>

<!ELEMENT RuleTemplate (Description*)>
<!ATTLIST RuleTemplate
   name CDATA #IMPLIED
   icon CDATA #IMPLIED
   file CDATA #IMPLIED
   process CDATA #IMPLIED
   workstep CDATA #IMPLIED
>


<!-- DesignerDeployment.xml -->

<!ELEMENT Deployment (Target*)>
<!ELEMENT Target (Label, Description*, Server+)>
<!ATTLIST Target
   url CDATA #IMPLIED
>

<!ELEMENT Label (#PCDATA)>

<!ELEMENT Server (#PCDATA)>
<!ATTLIST Server
        url CDATA #IMPLIED
>


<!-- DesignerFileTypes.xml -->

<!ELEMENT FileTypes (FileType*)>

<!ELEMENT FileType (OpenWith*)>
<!ATTLIST FileType
        name CDATA #IMPLIED
        ext CDATA #IMPLIED
>

<!ELEMENT OpenWith (#PCDATA)>
<!ATTLIST OpenWith
        name CDATA #IMPLIED
        command CDATA #IMPLIED
>

<!ELEMENT ManagedAdapter (#PCDATA)>
<!ATTLIST ManagedAdapter
  category CDATA #IMPLIED
  name CDATA #IMPLIED
>

<!-- DesignerResources.xml -->
<!ELEMENT Resources (Resource*)>

<!ELEMENT Resource (#PCDATA)>
<!ATTLIST Resource
   name		CDATA #IMPLIED
   unit		CDATA #IMPLIED
   value	CDATA #IMPLIED
   costPerUnit	CDATA #IMPLIED
   threshold	CDATA #IMPLIED
>

<!ELEMENT SwimLaneThemes (SwimLaneTheme*)>
<!ELEMENT SwimLaneTheme (Description?, SwimLane*)>
<!ATTLIST SwimLaneTheme
  name CDATA #IMPLIED
  default CDATA #IMPLIED
>

<!ELEMENT SwimLane (#PCDATA)>
<!ATTLIST SwimLane
  color	CDATA #IMPLIED
>

=== rpsinghc/maven-projects-springs/java9/conf/resources/designer/ModelerToolbar.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Toolbar SYSTEM "Designer.dtd" >
<Toolbar>
  <Palettes>
    <Palette mode="BizLogic">
      <Page name="Standard">
        <Description>Standard</Description>
        <Description xml:lang="ja">標準</Description>
        <Description xml:lang="zh">标准</Description>
        <Templates>
          <ComponentTemplate type="Start" name="Start">
            <NameTemplate count="false">Start</NameTemplate>
            <Description>Start</Description>
            <Description xml:lang="ja">スタート</Description>
            <Description xml:lang="zh">开始</Description>
          </ComponentTemplate>
          <ComponentTemplate type="Workstep" name="Activity">
            <NameTemplate>Activity {0}</NameTemplate>
            <Description>Activity</Description>
            <Description xml:lang="ja">アクティビティー</Description>
            <Description xml:lang="zh">活动</Description>
          </ComponentTemplate>
          <ComponentTemplate type="External" name="Adapter">
            <NameTemplate>Adapter {0}</NameTemplate>
            <Description>Adapter</Description>
            <Description xml:lang="ja">アダプター</Description>
            <Description xml:lang="zh">整合(集成)</Description>
          </ComponentTemplate>
          <ComponentTemplate type="Subprocess" name="Subprocess">
            <NameTemplate>Subprocess {0}</NameTemplate>
            <Description>Subprocess</Description>
            <Description xml:lang="ja">サブプロセス</Description>
            <Description xml:lang="zh">子流程</Description>
          </ComponentTemplate>
          <ComponentTemplate type="Decision" name="Decision">
            <NameTemplate>Decision {0}</NameTemplate>
            <Description>Decision</Description>
            <Description xml:lang="ja">条件分岐</Description>
            <Description xml:lang="zh">条件分支</Description>
          </ComponentTemplate>
          <ComponentTemplate type="AndJoin" name="And" width="40" height="40">
            <NameTemplate>And {0}</NameTemplate>
            <Description>And-join</Description>
            <Description xml:lang="ja">ＡＮＤ結合</Description>
            <Description xml:lang="zh">与</Description>
          </ComponentTemplate>
          <ComponentTemplate type="OrJoin" name="Or" width="40" height="40">
            <NameTemplate>Or {0}</NameTemplate>
            <Description>Or-join</Description>
            <Description xml:lang="ja">ＯＲ結合</Description>
            <Description xml:lang="zh">或</Description>
          </ComponentTemplate>
          <ComponentTemplate type="XorJoin" name="Xor" width="40" height="40">
            <NameTemplate>Xor {0}</NameTemplate>
            <Icon toolbar="xor.gif" diagram=""/>
            <Description>Xor-join</Description>
          </ComponentTemplate>
          <ComponentTemplate type="Split" name="Split" width="40" height="40">
            <NameTemplate>Split {0}</NameTemplate>
            <Description>Split</Description>
            <Description xml:lang="ja">分岐</Description>
            <Description xml:lang="zh">分支</Description>
          </ComponentTemplate>
          <ComponentTemplate type="End" name="End">
            <NameTemplate>End {0}</NameTemplate>
            <Description>End</Description>
            <Description xml:lang="ja">終了</Description>
            <Description xml:lang="zh">结束</Description>
          </ComponentTemplate>
        </Templates>
      </Page>
      <Page name="Notes">
        <Description>Notes</Description>
        <Description xml:lang="ja">ノート</Description>
        <Templates>
          <ComponentTemplate type="StickyNote" name="StickyNote" width="120" height="120">
            <NameTemplate count="false">Sticky note</NameTemplate>
            <Icon toolbar="stickyNote.gif" diagram=""/>
            <Description>Sticky note</Description>
            <Description xml:lang="ja">付箋紙</Description>
          </ComponentTemplate>
          <ComponentTemplate type="Annotation" name="Annotation" width="120" height="120">
            <NameTemplate count="false">Annotation</NameTemplate>
            <Icon toolbar="annotation.gif" diagram=""/>
            <Description>Annotation</Description>          
          </ComponentTemplate>
        </Templates>
      </Page>
    </Palette>
  </Palettes>
</Toolbar>

=== rpsinghc/maven-projects-springs/java9/conf/resources/designer/DesignerRules.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Rules SYSTEM "Designer.dtd" >
<Rules>
  <RuleCategory name="general">
    <Description>General</Description>
    <Description xml:lang="ja">一般</Description>
    <RuleTemplate name="NewRule" icon="new.gif" file="NewRule.rtu" process="true" workstep="true">
      <Description>New Rule</Description>
      <Description xml:lang="ja">新規ルール</Description>
      <Description xml:lang="zh">新规则</Description>
    </RuleTemplate>
    <RuleTemplate name="Schedule" icon="schedule.gif" file="Schedule.rtu" process="true" workstep="false">
      <Description>Schedule</Description>
      <Description xml:lang="ja">スケジュール</Description>
      <Description xml:lang="zh">超时</Description>
    </RuleTemplate>
  </RuleCategory>
  <RuleCategory name="notification">
    <Description>Notification</Description>
    <Description xml:lang="ja">通知</Description>
    <RuleTemplate name="ProcessPath" icon="processpath.gif" file="ProcessPath.rtu" process="true" workstep="true">
      <Description>Process Path</Description>
      <Description xml:lang="ja">プロセスパス</Description>
      <Description xml:lang="zh">监控</Description>
    </RuleTemplate>
    <RuleTemplate name="Timeout" icon="timeout.gif" file="Timeout.rtu" process="false" workstep="true">
      <Description>Time-Out</Description>
      <Description xml:lang="ja">タイムアウト</Description>
      <Description xml:lang="zh">超时</Description>
    </RuleTemplate>
  </RuleCategory>
  <RuleCategory name="metrics">
    <Description>Metrics</Description>
    <Description xml:lang="ja">メトリックス</Description>
    <RuleTemplate name="Monitor" icon="monitor.gif" file="Monitoring.rtu" process="true" workstep="true">
      <Description>Monitoring</Description>
      <Description xml:lang="ja">モニタ</Description>
      <Description xml:lang="zh">监控</Description>
    </RuleTemplate>    
    <RuleTemplate name="BusinessMetric" icon="businessmetric.gif" file="BusinessMetric.rtu" process="false" workstep="true">
      <Description>Business Metric</Description>
      <Description xml:lang="ja">ビジネスメトリック</Description>
      <Description xml:lang="zh">超时</Description>
    </RuleTemplate>
    <RuleTemplate name="DecisionCounter" icon="decisioncounter.gif" file="DecisionCounter.rtu" process="false" workstep="true">
      <Description>Decision Counter</Description>
      <Description xml:lang="ja">条件分岐カウンター</Description>
      <Description xml:lang="zh">超时</Description>
    </RuleTemplate>
  </RuleCategory>    
  <RuleCategory name="taskmanagement">
    <Description>Task Management</Description>
    <Description xml:lang="ja">タスク管理</Description>
    <RuleTemplate name="TaskAssignment" icon="taskassignment.gif" file="TaskAssignment.rtu" process="false" workstep="true">
      <Description>Task Assignment</Description>
      <Description xml:lang="ja">タスク割り当て</Description>
      <Description xml:lang="zh">超时</Description>
    </RuleTemplate>
  </RuleCategory>
  <RuleCategory name="integration">
    <Description>Integration</Description>
    <Description xml:lang="ja">インテグレーション</Description>
    <RuleTemplate name="ProcessControl" icon="processcontrol.gif" file="ProcessControl.rtu" process="true" workstep="false">
      <Description>ProcessControl</Description>
      <Description xml:lang="ja">プロセスコントロール</Description>
      <Description xml:lang="zh">超时</Description>
    </RuleTemplate>
    <RuleTemplate name="FilePoller" icon="filepoller.gif" file="FilePoller.rtu" process="true" workstep="false">
      <Description>FilePoller</Description>
      <Description xml:lang="ja">ファイルポーラー</Description>
      <Description xml:lang="zh">超时</Description>
    </RuleTemplate>    
  </RuleCategory>  
</Rules>

=== rpsinghc/maven-projects-springs/java9/conf/resources/designer/SwimLaneThemes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SwimLaneThemes SYSTEM "Designer.dtd" >

<!-- List of available swim lane themes -->
<SwimLaneThemes>
  <SwimLaneTheme name="colorful" default="true">
    <SwimLane color="red"/>
    <SwimLane color="yellow"/>
    <SwimLane color="lime"/>
    <SwimLane color="blue"/>
  </SwimLaneTheme>
  <SwimLaneTheme name="gray">
    <SwimLane color="gray"/>
    <SwimLane color="black"/>
  </SwimLaneTheme>
  <SwimLaneTheme name="red">
    <SwimLane color="red"/>
    <SwimLane color="maroon"/>
  </SwimLaneTheme>
  <SwimLaneTheme name="yellow">
    <SwimLane color="yellow"/>
    <SwimLane color="olive"/>
  </SwimLaneTheme>
  <SwimLaneTheme name="green">
    <SwimLane color="lime"/>
    <SwimLane color="green"/>
  </SwimLaneTheme>
  <SwimLaneTheme name="blue">
    <SwimLane color="blue"/>
    <SwimLane color="navy"/>
  </SwimLaneTheme>
</SwimLaneThemes>
