=== rpsinghc/maven-projects-springs/java9/conf/resources/designer/RuleWizards.dtd
<!-- RuleWizards.xml -->

 <!ELEMENT RuleWizards (RuleCategory*)>
 <!ELEMENT RuleCategory (Category*, RuleTemplate*)>
 <!ATTLIST RuleCategory
    name CDATA #IMPLIED
    visible CDATA #IMPLIED
 >

 <!ELEMENT Category (#PCDATA)>
 <!ATTLIST Category
   lang CDATA #IMPLIED
   xml:lang CDATA #IMPLIED
 >

 <!ELEMENT RuleTemplate (Process, Workstep, Description*)>

<!ELEMENT Description (#PCDATA)>
<!ATTLIST Description
  lang CDATA #IMPLIED
  xml:lang CDATA #IMPLIED
>

 <!ATTLIST RuleTemplate
    name CDATA #IMPLIED
    file CDATA #IMPLIED
    icon CDATA #IMPLIED
 >

  <!ELEMENT Process EMPTY>
  <!ATTLIST Process
     invoke CDATA #IMPLIED
  >

  <!ELEMENT Workstep EMPTY>
  <!ATTLIST Workstep
     invoke CDATA #IMPLIED
     type CDATA #IMPLIED
     performer CDATA #IMPLIED
     member CDATA #IMPLIED
  >

=== rpsinghc/maven-projects-springs/java9/conf/resources/designer/RuleWizards.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE RuleWizards SYSTEM "RuleWizards.dtd" >
<RuleWizards>
  <RuleCategory name="general" visible="true">
      <Category>General</Category>
      <Category xml:lang="ja">ja-General</Category>
      <Category xml:lang="zh">zh-General</Category>
      <Category xml:lang="fr">fr-General</Category>
      <RuleTemplate name="NewRule" file="NewRule.rtu" icon="new.gif">
        <Process invoke="true"/>
        <Workstep invoke="true"/>
        <Description>New rule</Description>
        <Description xml:lang="ja">ja-New rule</Description>
        <Description xml:lang="zh">zh-New rule</Description>
        <Description xml:lang="fr">fr-New rule</Description>
      </RuleTemplate>
      <RuleTemplate name="Schedule" file="Schedule.rtu" icon="schedule.gif">
        <Process invoke="true"/>
        <Workstep invoke="false"/>
        <Description>Schedule</Description>
        <Description xml:lang="ja">ja-Schedule</Description>
        <Description xml:lang="zh">zh-Schedule</Description>
        <Description xml:lang="fr">fr-Schedule</Description>
      </RuleTemplate>
  </RuleCategory>
  <RuleCategory name="notification" visible="true">
      <Category>Notification</Category>
      <Category xml:lang="ja">ja-Notification</Category>
      <Category xml:lang="zh">zh-Notification</Category>
      <Category xml:lang="fr">fr-Notification</Category>
      <RuleTemplate name="Timeout" file="Timeout.rtu" icon="timeout.gif">
        <Process invoke="false"/>
        <Workstep invoke="true" type="Activity"/>
        <Description>Timeout</Description>
        <Description xml:lang="ja">ja-Timeout</Description>
        <Description xml:lang="zh">zh-Timeout</Description>
        <Description xml:lang="fr">fr-Timeout</Description>
      </RuleTemplate>
      <RuleTemplate name="ProcessPath" file="ProcessPath.rtu" icon="processpath.gif">
        <Process invoke="true"/>
        <Workstep invoke="true" type="Activity"/>
        <Description>ProcessPath</Description>
        <Description xml:lang="ja">ja-ProcessPath</Description>
        <Description xml:lang="zh">zh-ProcessPath</Description>
        <Description xml:lang="fr">fr-ProcessPath</Description>
      </RuleTemplate>
  </RuleCategory>
  <RuleCategory name="metrics" visible="true">
      <Category>Metrics</Category>
      <Category xml:lang="ja">ja-Metrics</Category>
      <Category xml:lang="zh">zh-Metrics</Category>
      <Category xml:lang="fr">fr-Metrics</Category>
      <RuleTemplate name="Monitor" file="Monitoring.rtu" icon="monitor.gif">
        <Process invoke="true"/>
        <Workstep invoke="true" type="Activity"/>
        <Description>Monitoring</Description>
        <Description xml:lang="ja">ja-Monitoring</Description>
        <Description xml:lang="zh">zh-Monitoring</Description>
        <Description xml:lang="fr">fr-Monitoring</Description>
      </RuleTemplate>
      <RuleTemplate name="BusinessMetric" file="BusinessMetric.rtu" icon="businessmetric.gif">
        <Process invoke="false"/>
        <Workstep invoke="true" type="Activity"/>
        <Description>BusinessMetric</Description>
        <Description xml:lang="ja">ja-BusinessMetric</Description>
        <Description xml:lang="zh">zh-BusinessMetric</Description>
        <Description xml:lang="fr">fr-BusinessMetric</Description>
      </RuleTemplate>
      <RuleTemplate name="DecisionCounter" file="DecisionCounter.rtu" icon="decisioncounter.gif">
        <Process invoke="false"/>
        <Workstep invoke="true" type="Decision"/>
        <Description>DecisionCounter</Description>
        <Description xml:lang="ja">ja-DecisionCounter</Description>
        <Description xml:lang="zh">zh-DecisionCounter</Description>
        <Description xml:lang="fr">fr-DecisionCounter</Description>
      </RuleTemplate>
  </RuleCategory>
  <RuleCategory name="taskmanagement" visible="true">
      <Category>Task Management</Category>
      <Category xml:lang="ja">ja-Task Management</Category>
      <Category xml:lang="zh">zh-Task Management</Category>
      <Category xml:lang="fr">fr-Task Management</Category>
      <RuleTemplate name="TaskAssignment" file="TaskAssignment.rtu" icon="taskassignment.gif">
        <Process invoke="false"/>
        <Workstep invoke="true" type="Activity" performer="group" member="any"/>
        <Description>TaskAssignment</Description>
        <Description xml:lang="ja">ja-TaskAssignment</Description>
        <Description xml:lang="zh">zh-TaskAssignment</Description>
        <Description xml:lang="fr">fr-TaskAssignment</Description>
      </RuleTemplate>
  </RuleCategory>
  <RuleCategory name="integration" visible="true">
      <Category>Integration</Category>
      <Category xml:lang="ja">ja-Integration</Category>
      <Category xml:lang="zh">zh-Integration</Category>
      <Category xml:lang="fr">fr-Integration</Category>
      <RuleTemplate name="ProcessControl" file="ProcessControl.rtu" icon="processcontrol.gif">
        <Process invoke="true"/>
        <Workstep invoke="false"/>
        <Description>ProcessControl</Description>
        <Description xml:lang="ja">ja-ProcessControl</Description>
        <Description xml:lang="zh">zh-ProcessControl</Description>
        <Description xml:lang="fr">fr-ProcessControl</Description>
      </RuleTemplate>
      <RuleTemplate name="FilePoller" file="FilePoller.rtu" icon="filepoller.gif">
        <Process invoke="true"/>
        <Workstep invoke="false"/>
        <Description>FilePoller</Description>
        <Description xml:lang="ja">ja-FilePoller</Description>
        <Description xml:lang="zh">zh-FilePoller</Description>
        <Description xml:lang="fr">fr-FilePoller</Description>
      </RuleTemplate>
  </RuleCategory>
  <RuleCategory name="optimization" visible="false">
      <Category>Optimization</Category>
      <Category xml:lang="ja">ja-Optimization</Category>
      <Category xml:lang="zh">zh-Optimization</Category>
      <Category xml:lang="fr">fr-Optimization</Category>
      <RuleTemplate name="ProcessAnalysisWizard" file="ProcessAnalysisWizard.rtu" icon="schedule.gif">
        <Process invoke="true"/>
        <Workstep invoke="false"/>
        <Description>ProcessAnalysisWizard</Description>
        <Description xml:lang="ja">ja-ProcessAnalysisWizard</Description>
        <Description xml:lang="zh">zh-ProcessAnalysisWizard</Description>
        <Description xml:lang="fr">fr-ProcessAnalysisWizard</Description>
      </RuleTemplate>
  </RuleCategory>
</RuleWizards>
