=== rpsinghc/maven-projects-springs/java9/conf/resources/common/DatabaseMapping.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v4.2 U (http://www.xmlspy.com) by Deepak Gupta (P S Consultants) -->
<!--
This is the DTD file of DatabaseMapping.xml file.
Author: Deepak Gupta
Creation Date: September 18, 2001
-->
<!--
The sql-mapping element is the root element of the DatabaseMapping.xml
-->
<!ELEMENT sql-mapping (description?, data-source+)>
<!--
The type-mapping information consists of the following parts:
	The name of database vendor
	Mapping information.	

Used in: sql-mapping 
-->
<!ELEMENT data-source (max-table-name, record-size, read-only-transaction?, ddl-autocommit?, create-table?, type-mapping+)>
<!ATTLIST data-source
	name CDATA #REQUIRED
>
<!ELEMENT max-table-name (#PCDATA)>
<!ELEMENT record-size (#PCDATA)>
<!ELEMENT read-only-transaction (#PCDATA)>
<!ELEMENT ddl-autocommit (#PCDATA)>
<!ELEMENT type-mapping (description?, mapping+)>
<!--
The mapping contains the information for mapping java type
to database type. Also, it has two optional tags for specifying
the dataSlot type and maximum size of database type.

Used in: type-mapping 
-->
<!ELEMENT mapping (java?, dataslot?, database, database-mb?, size?, precision?, scale?)>
<!--
The description contains the optional description of sql-mapping.

Used in: sql-mapping, type-mapping 
-->
<!ELEMENT description (#PCDATA)>
<!--
The java element contains the fully qualified class name
of java type. For primitive types corresponding wrapper class
should be used. e.g. for int, value of java element will
be java.lang.Integer

Used in: mapping 
-->
<!ELEMENT java (#PCDATA)>
<!--
The database element contains the name database type (or SQL type)
e.g. NUMBER, VARCHAR etc. This element will not contain any size 
information e.g. VARCHAR (255) is not allowed here. For size information
separate element max-size is provided.

Used in: mapping 
-->
<!ELEMENT database (#PCDATA)>
<!--
The data-slot element is optional in mapping element. It contain the
String constants used in BizLogic 3.0/3.5 for dataSlot type
representation. It value could be STRING, DOUBLE, DOCUMENT, URL etc. All
dataSlot types are declared in PAKConstants class.

Used in: mapping 
-->
<!ELEMENT dataslot (#PCDATA)>
<!--
The max-size element contains the size information of database types.
e.g. in VARCHAR (255), the value 255 is contained by max-size element. 
This element is provided to prevent any overflow error caused by
storing the value exceeding the maximum allowed size.

Used in: mapping 
-->
<!ELEMENT size (#PCDATA)>
<!--
The precision element contains the precision information of double values.

Used in: mapping 
-->
<!ELEMENT precision (#PCDATA)>
<!--
The scale element contains the scale information of double values.

Used in: mapping 
-->
<!ELEMENT scale (#PCDATA)>
<!--
The database-mb element contains the SQL type for multibyte support.
e.g. NCHAR, NVARCHAR2 etc. This element will not contain any size 
information e.g. NVARCHAR (255) is not allowed here. For size information
separate element size is provided. In this case, size is the number of 
characters.

Used in: mapping 
-->
<!ELEMENT database-mb (#PCDATA)>

<!ATTLIST size
	bytes CDATA #IMPLIED
>

<!ELEMENT create-table (statement-suffix?)>
<!--
The create table element contains additional data that might be needed by a database for creating the table
for eg. Area Name that needs to be added at the end of the create table statement. 
while creating a table. 
-->
<!ELEMENT statement-suffix (#PCDATA)>
<!--
Contains a string that is appended at the end to the Create table statemnts for eg. Area AreaName
-->

=== rpsinghc/maven-projects-springs/java9/conf/resources/common/DatabaseMapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sql-mapping SYSTEM "DatabaseMapping.dtd" >
<sql-mapping>
    <data-source name="oracle">
        <max-table-name>30</max-table-name>
        <record-size>128000</record-size>
        <read-only-transaction>SET TRANSACTION READ ONLY</read-only-transaction>
        <ddl-autocommit>true</ddl-autocommit>
        <type-mapping>
            <mapping>
                <java>java.lang.Boolean</java>
                <dataslot>BOOLEAN</dataslot>
                <database>NUMBER</database>
                <size bytes="2">2</size>
            </mapping>
            <mapping>
                <java>java.lang.Integer</java>
                <dataslot>LONG</dataslot>
                <database>NUMBER</database>
                <size bytes="13">38</size>
            </mapping>
            <mapping>
                <java>java.lang.Long</java>
                <dataslot>LONG</dataslot>
                <database>NUMBER</database>
                <size bytes="13">38</size>
            </mapping>
            <mapping>
                <java>java.lang.Double</java>
                <dataslot>DOUBLE</dataslot>
                <database>NUMBER</database>
                <size bytes="13">38,15</size>
            </mapping>
            <mapping>
                <java>java.lang.String</java>
                <dataslot>STRING</dataslot>
                <database>VARCHAR2</database>
                <database-mb>NVARCHAR2</database-mb>
                <size bytes="4000">4000</size>
            </mapping>
            <mapping>
                <java>java.lang.Object</java>
                <dataslot>OBJECT</dataslot>
                <database>BLOB</database>
            </mapping>
            <mapping>
                <dataslot>URL</dataslot>
                <database>VARCHAR2</database>
                <database-mb>NVARCHAR2</database-mb>
                <size bytes="256">256</size>
            </mapping>
            <mapping>
                <dataslot>DOCUMENT</dataslot>
                <database>VARCHAR2</database>
                <database-mb>NVARCHAR2</database-mb>
                <size bytes="64">64</size>
            </mapping>
            <mapping>
                <java>java.sql.Timestamp</java>
                <dataslot>DATETIME</dataslot>
                <database>TIMESTAMP</database>
                <size bytes="13"/>
            </mapping>
            <mapping>
                <java>java.math.BigDecimal</java>
                <dataslot>DECIMAL</dataslot>
                <!-- the max precision allowed is 38. -->
                <!-- Scale is max of 15 in oracle     -->
                <database>DECIMAL</database>
                <size bytes="13">28,15</size>
            </mapping>
            <mapping>
                <java>java.math.BigDecimal</java>
                <dataslot>CURRENCY</dataslot>
                <database>DECIMAL</database>
                <size bytes="13">28,3</size>
            </mapping>
            <mapping>
                <java>java.lang.Long</java>
                <dataslot>XML</dataslot>
                <database>NUMBER</database>
                <size bytes="4"/>
            </mapping>
        </type-mapping>
    </data-source>
    <data-source name="mssqlserver">
        <max-table-name>128</max-table-name>
        <record-size>8039</record-size>
        <read-only-transaction></read-only-transaction>
        <ddl-autocommit>false</ddl-autocommit>
        <type-mapping>
            <mapping>
                <java>java.lang.Boolean</java>
                <dataslot>BOOLEAN</dataslot>
                <database>SMALLINT</database>
                <size bytes="2"/>
            </mapping>
            <mapping>
                <java>java.lang.Integer</java>
                <dataslot>LONG</dataslot>
                <database>BIGINT</database>
                <size bytes="8"/>
            </mapping>
            <mapping>
                <java>java.lang.Long</java>
                <dataslot>LONG</dataslot>
                <database>BIGINT</database>
                <size bytes="8"/>
            </mapping>
            <mapping>
                <java>java.lang.Double</java>
                <dataslot>DOUBLE</dataslot>
                <database>FLOAT</database>
                <size bytes="8"/>
            </mapping>
            <mapping>
                <java>java.lang.String</java>
                <dataslot>STRING</dataslot>
                <database>VARCHAR</database>
                <database-mb>NVARCHAR</database-mb>
                <size bytes="2000">2000</size>
            </mapping>
            <mapping>
                <java>java.lang.Object</java>
                <dataslot>OBJECT</dataslot>
                <database>IMAGE</database>
            </mapping>
            <mapping>
                <java>java.lang.String</java>
                <dataslot>URL</dataslot>
                <database>VARCHAR</database>
                <database-mb>NVARCHAR</database-mb>
                <size bytes="256">256</size>
            </mapping>
            <mapping>
                <java>java.lang.String</java>
                <dataslot>DOCUMENT</dataslot>
                <database>VARCHAR</database>
                <database-mb>NVARCHAR</database-mb>
                <size bytes="64">64</size>
            </mapping>
            <mapping>
                <java>java.sql.Timestamp</java>
                <dataslot>DATETIME</dataslot>
                <database>DATETIME</database>
                <size bytes="13"/>
            </mapping>
            <mapping>
                <java>java.math.BigDecimal</java>
                <dataslot>DECIMAL</dataslot>
                <database>DECIMAL</database>
                <!-- the max precision allowed is 28.  -->
                <!-- Scale is max of 28 in mssqlserver.-->
                <size bytes="13">28,15</size>
            </mapping>
            <mapping>
                <java>java.math.BigDecimal</java>
                <dataslot>CURRENCY</dataslot>
                <database>DECIMAL</database>
                <size bytes="13">28,3</size>
            </mapping>
            <mapping>
                <java>java.lang.Long</java>
                <dataslot>XML</dataslot>
                <database>INTEGER</database>
                <size bytes="4"/>
            </mapping>
        </type-mapping>
    </data-source>
    <data-source name="sybase">
        <!-- record size for sybase depends onthe page size -->
        <!--     page size           recordsize          -->
        <!--        2k                 1948              -->
        <!--        4k                 3988              -->
        <!--        8k                 8068              -->
        <!--        16k                16228             -->
        <!--   The default value is 1948 for 2k pagesize -->

        <!-- max size of a multi line string is dependent on the    -->
        <!-- page size of sybase. The max length of any multiline   -->
        <!-- string dataslot cannot exceed 2000 chars even if the   -->
        <!-- pg sz is more than 2000 chars. Please look for record  -->
        <!-- size relationship with pagesize above for more detail  -->
        <!-- page size           recommended  -->
        <!--               max multiline string size  -->
        <!--  2k                 256        -->
        <!--  4k                 256        -->
        <!--  8k                 2000       -->
        <!--  16k                2000       -->
        <!--The default value is 256 for 2k pagesize -->

        <max-table-name>30</max-table-name>
        <record-size>8068</record-size>
        <ddl-autocommit>true</ddl-autocommit>
        <type-mapping>
            <mapping>
                <java>java.lang.Boolean</java>
                <dataslot>BOOLEAN</dataslot>
                <database>TINYINT</database>
                <size bytes="1"></size>
            </mapping>
            <mapping>
                <java>java.lang.Integer</java>
                <dataslot>LONG</dataslot>
                <database>NUMERIC</database>
                <size bytes="17"/>
            </mapping>
            <mapping>
                <java>java.lang.Long</java>
                <dataslot>LONG</dataslot>
                <database>NUMERIC</database>
                <size bytes="17"/>
            </mapping>
            <mapping>
                <java>java.lang.Double</java>
                <dataslot>DOUBLE</dataslot>
                <database>DOUBLE PRECISION</database>
                <size bytes="8"/>
            </mapping>
            <mapping>
                <java>java.lang.String</java>
                <dataslot>STRING</dataslot>
                <database>VARCHAR</database>
                <database-mb>UNIVARCHAR</database-mb>
                <size bytes="2000">2000</size>
            </mapping>
            <mapping>
                <java>java.sql.Date</java>
                <dataslot>DATETIME</dataslot>
                <database>DATETIME</database>
                <size bytes="8"/>
            </mapping>
            <mapping>
                <java>java.lang.Object</java>
                <dataslot>OBJECT</dataslot>
                <database>IMAGE</database>
            </mapping>
            <mapping>
                <dataslot>URL</dataslot>
                <database>VARCHAR</database>
                <database-mb>UNIVARCHAR</database-mb>
                <size bytes="256">256</size>
            </mapping>
            <mapping>
                <dataslot>DOCUMENT</dataslot>
                <database>VARCHAR</database>
                <database-mb>UNIVARCHAR</database-mb>
                <size bytes="64">64</size>
            </mapping>
