=== rpsinghc/maven-projects-springs/java9/conf/resources/common/sbmcalendar.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!--
This is the DTD file of sbmcalendar.xml file.
Author: Vishnu Kumar trivedi
Creation Date: 25/09/2003 
-->
<!-- month = { Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec} -->
<!-- dow = {Sun, Mon, Tue, Wed, Thu, Fri, Sat} -->
<!-- day = 1 to 31 -->
<!-- occurence = {first, second, third, fourth, fifth, last, all} -->

<!--
The calendars element is the root element of the calendar.xml
-->
<!ELEMENT calendars (calendar?, persistence?)>

<!--
The calendar element 
-->
<!ELEMENT calendar (description?, locale?, timezone?, lunch-hours, business-hours,week-end?, fixed-holidays?, holidays*)>

<!--
 It specifies the persistence.
-->
<!ELEMENT persistence (provider, url, driver, user, passwd)>


<!--
 It specifies the database name like oracle, mssqlserver, etc.
-->
<!ELEMENT provider (#PCDATA)>

<!--
 It specifies the url.
-->
<!ELEMENT url (#PCDATA)>

<!--
 It specifies the driver.
-->
<!ELEMENT driver (#PCDATA)>

<!--
 It specifies the user.
-->
<!ELEMENT user (#PCDATA)>

<!--
 It specifies the passwd.
-->
<!ELEMENT passwd (#PCDATA)>

<!--
The description element is to specify a description 
-->
<!ELEMENT description (#PCDATA)>

<!--
The locale element is to specify the locale language and country
-->
<!ELEMENT locale (#PCDATA)>

<!--
The timzone element is to specify the timezone ID
-->
<!ELEMENT timezone (#PCDATA)>

<!--
The lunch-hours element contains the lunch hours information
-->
<!ELEMENT lunch-hours (#PCDATA)>

<!--
The business-hours element contains the business hours information
-->
<!ELEMENT business-hours (description?, business-hour*)>

<!--
The start element contains the empty information
-->
<!ELEMENT start-time (#PCDATA)>

<!--
The end element contains the empty information
-->
<!ELEMENT end-time (#PCDATA)>

<!--
The week-end element contains the week ends
-->
<!ELEMENT week-end (holiday+)>

<!--
The fixed-holidays element contains the fixed holidays
-->
<!ELEMENT fixed-holidays (holiday+)>

<!--
The holidays element contains the floating holidays
-->
<!ELEMENT holidays (holiday*)>

<!--
The holiday element contains the empty information
-->
<!ELEMENT holiday (#PCDATA)>

<!--
The business-hour element contains the empty information
-->
<!ELEMENT business-hour (#PCDATA)>

<!--
The attribute list of calendar element

name :- specifies the name of the calendar

-->
<!ATTLIST calendar 
        name CDATA #REQUIRED
>

<!--
The attribute list of locale element
language :- language for the locale
country :- country for the locale
-->
<!ATTLIST locale
        language CDATA #IMPLIED
        country CDATA #IMPLIED
>

<!--
The attribute list of timezone element
zoneid :- the ID for the timezone
-->
<!ATTLIST timezone
        zoneid CDATA #IMPLIED
>

<!--
The attribute list of holidays element

year :- specifies the year of the holidays element and year will be 4 digit number
-->
<!ATTLIST holidays 
        year CDATA #REQUIRED
        override CDATA #IMPLIED
>

<!--
The attribute list of holiday element

name :- specifies the name of the holiday
month :- specifies the month of the holiday, first three character of the month like
         { Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec}
day :- specifies the day of the holiday, first three character of the day like
         {Sun, Mon, Tue, Wed, Thu, Fri, Sat}
date :- specifies the any date of the holiday from 1 to 31
occurrence :- specifies the occurrence of the holiday 
             occurrence will be {first, second, third, fourth, fifth, last and all}
first-half :- true means that first half is a holiday.
second-half :- true means that second half is a holiday.
-->
<!ATTLIST holiday 
        name CDATA #REQUIRED
        first-half CDATA #IMPLIED
        second-half CDATA #IMPLIED
        month CDATA #IMPLIED
        day CDATA #IMPLIED
        dow CDATA #IMPLIED
        occurrence CDATA #IMPLIED
>

<!--
The attribute list of business-hour element

start-time :- start time of the day
end-time :- end time of the day
year :- specifies the year
month :- specifies the month, first three character of the month like
         { Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec}
day :- specifies the any date from 1 to 31
dow :- specifies the day of the week, first three character of the day like
         {Sun, Mon, Tue, Wed, Thu, Fri, Sat}
-->
<!ATTLIST business-hour 
        start-time CDATA #REQUIRED
        end-time CDATA #REQUIRED
        year CDATA #IMPLIED
        month CDATA #IMPLIED
        day CDATA #IMPLIED
        dow CDATA #IMPLIED
>

<!--
The attribute list of lunch-hours element

start-time :- start time of the lunch
end-time :- end time of the lunch
-->
<!ATTLIST lunch-hours 
        start-time CDATA #REQUIRED
        end-time CDATA #REQUIRED
>

=== rpsinghc/maven-projects-springs/java9/conf/resources/common/sbmcalendar.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE calendars SYSTEM "sbmcalendar.dtd">

<!-- year = 4 digit number -->
<!-- month = { Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec} -->
<!-- dow = {Sun, Mon, Tue, Wed, Thu, Fri, Sat} -->
<!-- day = 1 to 31 -->
<!-- occurence = {first, second, third, fourth, fifth, last, all} -->
<calendars>
    <calendar name="sbmcalendar">
        <description>SBM Calendar</description>

        <locale language="en" country="US"/>
        <timezone zoneid="America/Los_Angeles"/>

        <lunch-hours start-time="1200" end-time="1300"/>

        <business-hours>
            <description>business hours</description>
            <business-hour start-time="0800" end-time="1700"/>
        </business-hours>

        <week-end>
            <holiday name="Sunday" dow="Sun" />
            <holiday name="Saturday" dow="Sat" />
        </week-end>

        <!-- Fixed holidays are the ones that dont change over the years like New Year, 
             President's day, Memorial Day
        -->
        <fixed-holidays>
            <holiday name="New Year Day" month="Jan" day="1"/>
            <holiday name="President Day" month="Feb" dow="Mon" occurrence="third"/>
            <holiday name="Memorial Day" month="May" dow="Mon" occurrence="last"/>
            <holiday name="Independence Day" month="Jul" day="4"/>
            <holiday name="Labor Day" month="Sep" dow="Mon" occurrence="first"/>
            <holiday name="Thanks Giving Day" month="Nov" dow="Thu" occurrence="last"/>
            <holiday name="Christmas Eve" month="Dec" day="24"/>
            <holiday name="Christmas" month="Dec" day="25"/>
        </fixed-holidays>

        <!-- Additional holidays for specific years. Typically these are floating holidays 
             or compensatory holidays for fixed holidays that fall on weekends
        -->
        <holidays year="2005" override="true">
            <holiday name="New Year's Day Sub" month="Jan" day="3"/>
            <holiday name="Day After Thanks Giving" month="Nov" day="25"/>
            <holiday name="Christmas Eve Sub" month="Dec" day="26"/>
            <holiday name="Christmas Sub" month="Dec" day="27"/>
            <holiday name="New Year's Eve Sub" month="Dec" day="30"/>
        </holidays>
        <holidays year="2006" override="true">
            <holiday name="New Year's Day Sub" month="Jan" day="2"/>
            <holiday name="New Year's Eve Sub" month="Dec" day="29"/>
            <holiday name="Christmas Eve Sub" month="Dec" day="22"/>
            <holiday name="Day After Thanks Giving" month="Dec" day="1"/>
        </holidays>

    </calendar>
</calendars>
